spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.33.10/assign
    username: dorakucommitters
    password: dorakucommitters
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
spring.jpa.hibernate.ddl-auto: none
spring.thymeleaf.cache: false
