spring:
  datasource:
    url: jdbc:mysql://192.168.33.10/assign
    username: dorakucommitters
    password: dorakucommitters
    driverClassName: com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto: none
spring.thymeleaf.cache: false
